FROM nginx:alpine as production-build
LABEL maintainer="Eddie Rantsimele<ed@reanimate.io>"

COPY ./nginx/nginx.production.conf /etc/nginx/nginx.conf

## Remove default nginx index page
RUN rm -rf /usr/share/nginx/html/*


COPY ./dist /usr/share/nginx/html

EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
