
# File: .github/workflows/workflow.yml
permissions:
  contents: read
  pages: write
  id-token: write

on:
  workflow_dispatch:

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        az webapp list --query "[?state=='Running']"
