on:
  workflow_dispatch:

name: AzureLoginSample2

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        #creds: ${{ secrets.AZURE_CREDENTIALS }}
        client-id: ${{ secrets.CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
    
    - run: |
        az webapp list --query "[?state=='Running']"
